In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
pwd

'E:\\Projects\\Krishnaik\\AQI-Project-master'

In [4]:
df=pd.read_csv('Data/Real-Data/Real_Combine.csv')

In [5]:
df=df.dropna()

In [6]:
X=df.iloc[:,:-1] ## independent features
y=df.iloc[:,-1] ## dependent features

In [7]:
from sklearn.ensemble import ExtraTreesRegressor
import matplotlib.pyplot as plt
model = ExtraTreesRegressor()
model.fit(X,y)

ExtraTreesRegressor()

In [8]:
print(model.feature_importances_)

[0.18169262 0.08841266 0.24236713 0.12437554 0.08921405 0.18014413
 0.05235564 0.04143824]


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [10]:
X_train.shape

(764, 8)

In [17]:
!pip install keras


  Using cached Keras-2.4.3-py2.py3-none-any.whl (36 kB)


In [18]:
# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from tensorflow.keras import layers
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

In [22]:
NN_model = Sequential()

# The Input Layer :
NN_model.add(Dense(128, kernel_initializer='normal',input_dim = X_train.shape[1], activation='relu'))

# The Hidden Layers :
NN_model.add(Dense(256, kernel_initializer='normal',activation='relu'))
NN_model.add(Dense(256, kernel_initializer='normal',activation='relu'))
NN_model.add(Dense(256, kernel_initializer='normal',activation='relu'))

# The Output Layer :
NN_model.add(Dense(1, kernel_initializer='normal',activation='linear'))

# Compile the network :
NN_model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_error'])
NN_model.summary()

# Fitting the ANN to the Training set
model_history=NN_model.fit(X_train, y_train,validation_split=0.33, batch_size = 10, epochs = 100)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 128)               1152      
_________________________________________________________________
dense_16 (Dense)             (None, 256)               33024     
_________________________________________________________________
dense_17 (Dense)             (None, 256)               65792     
_________________________________________________________________
dense_18 (Dense)             (None, 256)               65792     
_________________________________________________________________
dense_19 (Dense)             (None, 1)                 257       
Total params: 166,017
Trainable params: 166,017
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
52/52 [==============================] - 3s 14ms/step - loss: 83.4050 - mean_absolute_error: 83.4050 -

Epoch 44/100
52/52 [==============================] - 0s 4ms/step - loss: 39.9378 - mean_absolute_error: 39.9378 - val_loss: 46.2976 - val_mean_absolute_error: 46.2976
Epoch 45/100
52/52 [==============================] - 0s 4ms/step - loss: 40.0705 - mean_absolute_error: 40.0705 - val_loss: 50.5686 - val_mean_absolute_error: 50.5686
Epoch 46/100
52/52 [==============================] - 0s 4ms/step - loss: 44.1930 - mean_absolute_error: 44.1930 - val_loss: 45.3175 - val_mean_absolute_error: 45.3175
Epoch 47/100
52/52 [==============================] - 0s 4ms/step - loss: 41.2280 - mean_absolute_error: 41.2280 - val_loss: 44.6526 - val_mean_absolute_error: 44.6526
Epoch 48/100
52/52 [==============================] - 0s 5ms/step - loss: 39.9027 - mean_absolute_error: 39.9027 - val_loss: 43.9281 - val_mean_absolute_error: 43.9280
Epoch 49/100
52/52 [==============================] - 0s 4ms/step - loss: 39.0699 - mean_absolute_error: 39.0699 - val_loss: 44.0531 - val_mean_absolute_error: 

Epoch 93/100
52/52 [==============================] - 0s 5ms/step - loss: 39.4141 - mean_absolute_error: 39.4141 - val_loss: 47.0832 - val_mean_absolute_error: 47.0832
Epoch 94/100
52/52 [==============================] - 0s 4ms/step - loss: 41.2225 - mean_absolute_error: 41.2225 - val_loss: 44.9211 - val_mean_absolute_error: 44.9211
Epoch 95/100
52/52 [==============================] - 0s 5ms/step - loss: 40.9926 - mean_absolute_error: 40.9926 - val_loss: 43.3404 - val_mean_absolute_error: 43.3404
Epoch 96/100
52/52 [==============================] - 0s 5ms/step - loss: 41.4957 - mean_absolute_error: 41.4957 - val_loss: 48.5757 - val_mean_absolute_error: 48.5757
Epoch 97/100
52/52 [==============================] - 0s 5ms/step - loss: 40.9688 - mean_absolute_error: 40.9688 - val_loss: 43.2418 - val_mean_absolute_error: 43.2418
Epoch 98/100
52/52 [==============================] - 0s 5ms/step - loss: 39.9549 - mean_absolute_error: 39.9549 - val_loss: 43.5343 - val_mean_absolute_error: 

In [23]:
prediction=NN_model.predict(X_test)

In [25]:
y_test.shape

(328,)

In [29]:
y_test.values

array([104.625     , 125.89166667, 279.6       , 110.41666667,
        31.33333333,  69.66666667, 278.        , 119.70833333,
        45.95833333, 135.58333333,  87.83333333, 173.58333333,
        12.25      ,  78.54166667, 115.83333333, 173.58333333,
       319.7375    , 203.58333333,  79.83333333, 152.32083333,
         0.        ,  26.66666667, 146.20833333, 108.        ,
       137.125     ,  75.58333333,  38.25      , 149.58333333,
         0.        ,  76.54166667, 101.95833333, 109.33333333,
        99.5       ,  15.16666667,  43.66666667,  68.91666667,
       284.79583333,  47.25      ,  23.20833333,   0.        ,
        57.58333333,  38.25      , 184.20833333, 133.375     ,
         1.91666667, 115.83333333,  26.41666667,  87.83333333,
        77.70833333,  98.41666667, 276.90833333,  95.83333333,
       349.29166667, 101.        ,  43.66666667,  43.66666667,
        54.79166667, 122.5       ,  25.79166667,  32.95833333,
        40.625     , 117.58333333,  36.        , 186.04

In [28]:
y_test.values.reshape(-1,1)

array([[104.625     ],
       [125.89166667],
       [279.6       ],
       [110.41666667],
       [ 31.33333333],
       [ 69.66666667],
       [278.        ],
       [119.70833333],
       [ 45.95833333],
       [135.58333333],
       [ 87.83333333],
       [173.58333333],
       [ 12.25      ],
       [ 78.54166667],
       [115.83333333],
       [173.58333333],
       [319.7375    ],
       [203.58333333],
       [ 79.83333333],
       [152.32083333],
       [  0.        ],
       [ 26.66666667],
       [146.20833333],
       [108.        ],
       [137.125     ],
       [ 75.58333333],
       [ 38.25      ],
       [149.58333333],
       [  0.        ],
       [ 76.54166667],
       [101.95833333],
       [109.33333333],
       [ 99.5       ],
       [ 15.16666667],
       [ 43.66666667],
       [ 68.91666667],
       [284.79583333],
       [ 47.25      ],
       [ 23.20833333],
       [  0.        ],
       [ 57.58333333],
       [ 38.25      ],
       [184.20833333],
       [133

In [30]:
prediction

array([[ 95.24366 ],
       [169.24797 ],
       [153.9536  ],
       [ 54.624836],
       [ 35.326008],
       [126.481636],
       [161.02504 ],
       [159.68092 ],
       [ 45.371613],
       [188.45116 ],
       [ 83.61987 ],
       [ 58.87601 ],
       [ 33.536694],
       [ 54.921307],
       [ 70.93991 ],
       [ 58.87601 ],
       [215.31302 ],
       [135.00426 ],
       [ 40.341976],
       [167.02527 ],
       [ 37.799416],
       [ 47.631203],
       [ 35.14895 ],
       [ 93.31586 ],
       [125.50948 ],
       [ 91.963936],
       [ 41.08601 ],
       [ 76.62509 ],
       [ 37.005726],
       [ 81.51954 ],
       [ 82.19034 ],
       [141.43806 ],
       [ 62.193356],
       [ 70.13866 ],
       [ 42.625637],
       [ 82.899895],
       [209.2965  ],
       [ 70.51143 ],
       [ 91.71941 ],
       [178.2793  ],
       [ 33.710655],
       [ 41.72948 ],
       [115.40208 ],
       [109.079956],
       [ 76.665344],
       [ 70.93991 ],
       [ 38.148502],
       [ 83.6